### ISSUE TITLE
Docker stops working after 1-2 days

### ISSUE THREAD

**Issue by Nighthawk79** [tillsteinbach/WeConnect-mqtt#239] opened 2023-07-22 14:16 UTC
Hi Till,

I'm using WeConnect-mqtt since more than one year.
Since couple of weeks there is an issue with Weconnect-mqtt wich stops working (no new data is provided) without any error message or log entry wile docker image seems to continue running.
Could you please explain how to find the root cause for this problem?

**Comment by tillsteinbach** [comment] 2023-07-22 17:57
Hey, thanks for reporting, can you try v0.45.1 for me? I believe this could solve your problem.

**Comment by Nighthawk79** [comment] 2023-07-23 10:25
Hi Till,

thank you for the fast  reaction. 
I've just updated the Image and will report  after a couple of days.

**Comment by hanjuq** [comment] 2023-08-28 07:49
Hi Till,

maybe my problem has same root cause:
I run weconnect-mqtt on Synology-Docker. A homeassistant container is running as a consumer for your mqtt stuff.

After nightly scheduled stop and restart HA was missing some(!) mqtt topics, i.e.:
weconnect/0/vehicles/.../domains/measurements/odometerStatus/odometer

while others still have been updated, i.e.:
weconnect/0/mqtt/weconnectConnected  (= True!)
weconnect/0/mqtt/weconnectUpdated
weconnect/0/vehicles/.../domains/charging/batteryStatus/currentSOC_pct

With my MQTT.fx tool I subscribed the odometer topic and nothing was received. That means: weconnect did not only stop publishing, it wrote an empty payload to this topic (as I know the only way to delete a retained topic)!

Restart of weconnect-mqtt made everything working fine again.

B.T.W.: actually the weconnect homeassistant integration from robinostlund has a login issue. This fact caused me to install weconnect-mqtt. Some other homeassistant users are now discussing your weconnect-mqtt as an emergency exit.

**Comment by andlo** [comment] 2023-08-28 08:15
I have setup a docker addon on HAOS, and it has been rock solid over the weekend. Getting data fast and continusly. Great alternative to the weconnect homeassistant integration from robinostlund so far.

**Comment by hanjuq** [comment] 2023-08-29 10:13
Just while I'm writing this comment, my weconnect-mqtt container is running. But again - as I posted above - some topics do no longer exist.

A scan with MQTT.fx produces this list:
[topcis_before_restart.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/12463002/topcis_before_restart.txt)

Now I restart weconnect-mqtt and as you can see, with 22 more topics it's complete:
[topcis_after_restart.txt](https://github.com/tillsteinbach/WeConnect-mqtt/files/12463094/topcis_after_restart.txt)

(The capabilities are disabled with --no-capabilities.)

**Comment by jeremylittleoaks** [comment] 2023-10-25 14:24
Seem to have the same issue as hanjuq - after a few hours topics cease to exist but come back on restart.  weconnect-mqtt is not running in docker but on a separate linux platform.  Again using this with mosquitto under Home Assistant.  Jeremy

**Comment by hanjuq** [comment] 2023-10-26 08:20
In the meantime I switched to a self written solution based on WeConnect-python (thanks to Till!!). It's running now for one month without any issue. To make it stable I had to implement exception handling for every(!) usage of that lib.

Jürgen

**Comment by jeremylittleoaks** [comment] 2023-10-30 15:56
Thanks - have updated to 0.48.2 and will report back

**Comment by Nighthawk79** [comment] 2024-01-01 16:53
Hi Till,

this Bug seems  to be solved now, it works since couple of weeks without any issue.
Thanks for the fix!

br
Alex

**Comment by tillsteinbach** [comment] 2024-01-01 19:13
Thank you for reporting. I close this one for now.

**Closed by tillsteinbach** 2024-01-01 19:13 UTC
Labels: bug, in testing
